name = "lsji"
main = "worker.js"
compatibility_date = "2024-04-01"

[triggers]
crons = ["*/8 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "lsji-db"
database_id = "9ea324c7-419b-4643-ae75-4d60adb7fe36" # ここに実際のIDを入れてください
